title:              Daniil Azarov
email:              azarov.dj@gmail.com
description:        This a personal website of Daniil Azarov
author:             Start Bootstrap
baseurl:            ""
url:                "https://DaniilAzarov123.github.io"

# Social Profiles
twitter_username:   
github_username:    DaniilAzarov123
facebook_username:  
instagram_username: danil_azarov_ 
linkedin_username: www.linkedin.com/in/daniil-azarov-998584355

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
